### ISSUE TITLE
Have you considered doing this w/o Kinect?

### ISSUE THREAD

**Issue by djMax** [sunlightlabs/vigo#1]
I'm going to give it a go, but I wonder if you have a fixed distance sidewalk (we do) whether the Kinect part is basically not important?

**Comment by konklone** [comment]
The Kinect's main value was recognizing human skeletons, even though this was just using the simplest/quickest algorithm for it and not actually looking at the individual joints (which it could also do, but required a calibration step not suited for gatherings of people).

I think you could do this with anything that could detect motion and give you a center point of the shape that's doing the moving, and I bet a lot of things could do that.
